### ISSUE TITLE
Adding more leds and buttons.

### ISSUE THREAD

**Issue by gokhantuncel** [James-Blackledge/Arduino-Project#1]
I wanted to increase leds and buttons to 9 but I stacked at some point. I want to have 9 leds and buttons with sequences of 3 - 4 and maybe 5 leds to light up and wait for input. I tried but couldn't find where to change for that, I only achieved to add led and button pins and light up 9 sequence :) So, maybe you can help me on this as you are the code owner.
[BottonTestGame.ino.zip](https://github.com/James-Blackledge/Arduino-Project/files/1429311/BottonTestGame.ino.zip)

**Comment by jamesblkledge** [comment]
Sorry for the late response. I have not been able to have each LED flash in sequences of 3 - 4, however the code should now randomly flash across all 9 LEDs. I have not been able to test the program as I do not own an Arduino (I borrowed it since this was originally a school project).
[ButtonTestGame.zip](https://github.com/James-Blackledge/Arduino-Project/files/1467460/ButtonTestGame.zip)
